server:
  port: 8000

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_services_db
    username: postgres
    password: manhden123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    #    mức độ log mặc đinh
    root: INFO
    #    giảm log của spring
    org.springframework: WARN
    #    log tri tiết cho code
    com.example.authservice: debug
  #    định dạng log trên console
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

  file:
    name: logs/auth-service.log

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  signerKey: 6giN96QESBj+R55/5N569HKuj0bL6x7j4+ShDZXh1ui6ay/FjtRzFfUC0Na21/c2
