server:
  error:
    include-message: always       # Trả message lỗi cho client
    include-exception: false      # Không trả tên exception
    include-stacktrace: never     # ⛔️ Không trả trace stack
    whitelabel:
      enabled: false              # Tắt giao diện lỗi mặc định
  port: 8081

spring:
  application:
    name: user-service

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog.sql

  datasource:
    url: jdbc:postgresql://localhost:5432/user_services_db
    username: postgres
    password: manhden123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    org.springframework: WARN
    com.example.productservice: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/user-service.log


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  signerKey: "oXQ/C4Jx7y3Hzze1KFqpE88NhrCOzUJ+gH8Bj5rDn0bcLDPk16uSzfI4VRSuKGi5"
